services:
  shellngn-pro:
    image: shellngn/pro:latest
    container_name: shellngn-pro
    ports:
      - "8097:8080"
    environment:
      HOST: 0.0.0.0
    volumes:
      - shellngn-data:/home/node/server/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shellngn.rule=Host(`shellngn.docker-1.gwebs.ca`)"
      - "traefik.http.routers.shellngn.entrypoints=websecure"
      - "traefik.http.routers.shellngn.tls=true"
      - "traefik.http.routers.shellngn.tls.certresolver=le"
      - "traefik.http.routers.shellngn-insecure.rule=Host(`shellngn.docker-1.gwebs.ca`)"
      - "traefik.http.routers.shellngn-insecure.entrypoints=web"
      - "traefik.http.routers.shellngn-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.shellngn.loadbalancer.server.port=8080"
    networks:
      - traefik_default

volumes:
  shellngn-data:

networks:
  traefik_default:
    external: true
