services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:5
    restart: unless-stopped
    volumes:
      - /Apps/upsnap/:/app/pb_data
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.upsnap.loadbalancer.server.port=5000"
      - "traefik.http.routers.upsnap.rule=Host(`upsnap.docker-1.gwebs.ca`) || Host(`upsnap.docker-2.gwebs.ca`)"
      - "traefik.http.routers.upsnap.entrypoints=websecure"
      - "traefik.http.routers.upsnap.tls=true"
      - "traefik.http.routers.upsnap.tls.certresolver=le"
      - "traefik.http.routers.upsnap-insecure.rule=Host(`upsnap.docker-1.gwebs.ca`) || Host(`upsnap.docker-2.gwebs.ca`)"
      - "traefik.http.routers.upsnap-insecure.entrypoints=web"
      - "traefik.http.routers.upsnap-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.upsnap.loadbalancer.server.scheme=http"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true