global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.10.5:9100']
        labels:
          instance: 'DNS-1'
      - targets: ['192.168.15.5:9100']
        labels:
          instance: 'DNS-2'
      - targets: ['192.168.10.13:9100']
        labels:
          instance: 'Plex-1'
      - targets: ['192.168.10.12:9100']
        labels:
          instance: 'NAS-1'
      - targets: ['192.168.10.14:9100']
        labels:
          instance: 'Gaming-1'
      - targets: ['192.168.10.11:9100']
        labels:
          instance: 'Docker-1'
      - targets: ['192.168.15.11:9100']
        labels:
          instance: 'Docker-2'
      - targets: ['192.168.10.10:9100']
        labels:
          instance: 'PVE-1'
      - targets: ['192.168.15.10:9100']
        labels:
          instance: 'PVE-2'
      - targets: ['100.80.8.22:9100']
        labels:
          instance: 'PSC-PBS-VM1'
#      - targets: ['192.168.10.20:9100']
#        labels:
#          instance: 'k8s-master-1'
#      - targets: ['192.168.10.21:9100']
#        labels:
#          instance: 'k8s-worker-1'
#      - targets: ['192.168.15.22:9100']
 #       labels:
#          instance: 'k8s-worker-2'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.10.5:8091']
        labels:
          instance: 'DNS-1'
      - targets: ['192.168.15.5:8091']
        labels:
          instance: 'DNS-2'
      - targets: ['192.168.10.13:8091']
        labels:
          instance: 'Plex-1'
      - targets: ['192.168.10.11:8091']
        labels:
          instance: 'Docker-1'
      - targets: ['192.168.15.11:8091']
        labels:
          instance: 'Docker-2'