$ANSIBLE_VAULT;1.1;AES256
36356162323031363232363634343631646235653138656133303639336566613930613364316662
3734323863386530393662653166306563376632626236360a353637313262626531613264356539
32373235336430303332616139323633363335396633646231336563356265656365346661366461
3835366664343161330a613965396165663665323939303434636466333131633035313061356533
32373735303432386361336533313964663464633261326661386563613665343532313639333136
39633330373031616539326638353762656639326361393835323765653532616535306262393638
38383734666666393262356437363863363866616262336139386631393265376334653735383962
62396135643632613132
