# ansible-lint skip: risky-file-permissions

- name: Setup NAS-1
  hosts: NAS-1
  order: sorted
  become: true

  vars:
    homelab_repo_root: "{{ playbook_dir }}/../.."

  tasks:

    - name: Install ACL
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Install Samba
      ansible.builtin.apt:
        name: samba
        state: present

    - name: Install Sanoid
      ansible.builtin.apt:
        name: sanoid
        state: present

    - name: Install Rclone
      ansible.builtin.apt:
        name: rclone
        state: present

    - name: Install Smartmontools
      ansible.builtin.apt:
        name: smartmontools
        state: present

    - name: Ensure /etc/sanoid directory exists
      ansible.builtin.file:
        path: /etc/sanoid
        state: directory

    - name: Copy sanoid.conf
      ansible.builtin.copy:
        src: "{{ homelab_repo_root }}/etc/sanoid/sanoid.conf"
        dest: /etc/sanoid/sanoid.conf

    - name: Enable and start sanoid.timer
      ansible.builtin.systemd:
        name: sanoid.timer
        enabled: true
        state: started

    - name: Copy smb.conf
      ansible.builtin.copy:
        src: "{{ homelab_repo_root }}/etc/samba/smb.conf"
        dest: /etc/samba/smb.conf
