---
- name: Update Ubuntu servers
  hosts: linux_vms
  become: true
  gather_facts: false
  strategy: free
  ignore_unreachable: true

  pre_tasks:
    - name: Check host reachability
      ansible.builtin.import_role:
        name: common
        tasks_from: check_reachability

    - name: Gather facts
      ansible.builtin.setup:

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
      when: ansible_facts is defined

    - name: Check if docker is installed
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker_stat
      when: ansible_facts is defined

    - name: Run 'docker system prune -a'
      ansible.builtin.command: docker system prune -af
      when:
        - docker_stat is defined
        - docker_stat.stat is defined
        - docker_stat.stat.exists | default(false)