services:
  jokedejean:
    image: gitea.docker-1.gwebs.ca/gabriel/jokedejean:latest
    container_name: jokedejean
    restart: unless-stopped
    environment:
      - LOAD_REDDIT=true
    volumes:
      - /Apps/jokedejean:/app/discordbot/data/